# Generated by Django 2.2.18 on 2025-06-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_auto_20250601_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='cencureshipflag',
            field=models.IntegerField(default=0),
        ),
    ]
