# Generated by Django 2.2.18 on 2025-06-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_video_cencureshipflag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='cencureshipflag',
            new_name='censorship_flag',
        ),
    ]
